### ISSUE TITLE
Incorrect User Detection in Fingerprint System

### ISSUE THREAD

**Issue by windsleigh** [AlvaroParker/lab-control#10]
Description:

When a user checks in by pressing their fingerprint, the system automatically records the event in the logs. However, it has been observed that occasionally the fingerprint sensor incorrectly associates the fingerprint with the wrong user. This could lead to inaccurate logging and potential confusion in the system.
Steps to Reproduce:

    User presses their fingerprint on the sensor for check-in.
    System sometimes registers the wrong user in the logs.

Expected Behavior:

    The system should always associate the correct user with their fingerprint.
    If the system cannot confidently match the fingerprint, it should prompt the user to confirm their identity before logging the event.

Proposed Solution:

    Implement a confirmation step after the fingerprint is detected.
    Before logging the check-in, the system should display the detected user’s information and ask for user confirmation (e.g., a "Yes/No" prompt).
    Only proceed with logging the check-in once the user confirms that the system detected the correct identity.

Impact:

This feature will reduce incorrect user logs and improve the system’s accuracy in recording attendance.

**Comment by VittorioCancino** [comment]
Please add this functionality. I manage the entire record-keeping for my company, and I can't afford more issues because my employees are not being correctly detected by the fingerprint reader, which causes their work hours to be recorded incorrectly and results in them not receiving their pay for working.
